language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "brus2c9y+SSEtqSZUXxluckjHb0WJokhtJhjXiF85azEfIx3Rdmwl2bbA4X1gLsDlR594ZjnxAOYMfjQcYesl5AqnNil4lDmJBPiwAXnAXm4DkMbN5VIfFnea93d+pyZFmjTY6YK9slJCzfnQDS/4Tr9EXoRKv+a9ve+Hk9S505ln4iDn2nxYuRJYtEFFLeBTO7aHJFmUpxJZcoAPM6ZLnpH2YAgVg0daFugBT2iPvnPVktPS8vm+JG0aO9T9SHfDNGpOgZPQ00jYpHAx8kCEnia6MdpGFI+llx1whvQqoOa2PxU/YyZu+PsbRy4pA1apvdmS7MrWGNKSUZqwnPLFiA8wNWRPsTBTFTjP1zpt20Cxq71C4dK2rPGdWAOr/Yee3D5fnrru8vHZ9zc6GTOg2KdGs15OvWtqPXix+hryg9drgatIEUZStkkv6rqTPsCk3vgUV9zvJOL0qrCQPkZ7ooDL5ilM7ewwLgnMbhJZ9to1xXXn8lCPpvPkEWykLTyNZbseyMoyp4al/OEDJp/GMSrPJjIgYiJdiNwZxRH2HqZLlv3kOUW571Op7vyx4FRDFY4MX54MinGSyT+bWVwH9mEhfbmuhXaft+2CxDr8QB5lhe6F1C0i/Zm3XNzbzUbUq+PwSX6i05KVr1Un5xFH+GLO8n5+SJ9XxgoClVZpJc="
    - secure: "rm5DovbmGbkGkbF2/lLdTJsEqiK5XYvRNnGHaWlvsedVZXzHvPCPfj5nR5rWCWPD9fBGY51iPr2O00OuCAQowPlKn0eDdF3KGlDIr08FiWQWwZuT+LMh2rsTYVySEeBRyFZe7UqPzpepOQwiBQZpljVzURtVkE6WMVWeAPKNFstXWJAS6afJO1CVGqzTPhRYYDjR/l6VIhdRsGXxeMrk3OAH1g000RKxG7C4LaL3nZugD1M2owOQ/MAnrheCJi1uWChA6yhnMzVrd93C2a7wTTZ9tNf24176CFDz0v3XQcOIet6rpMfJK8Rh/nfEbDFb+PM9thS195yfhGTK4oWrwdpIe/vAKgQkhZc1HDfbEjV/g44vjDnxEF5WclJrQqXZqG0AaEJYQtC89MW50WXjGjq1mi4Ej80/5wcIhiRNO4ohYFhEqw/0mmqRw5Kbc/wGGWS5TMjKaZ3G+Gbr4dT3GfCyzWfi81lFfDb0CLahQseP2CJKqNJDpi4WKjjlqGCaAOfecomwOk536IVIDu7C7P3oRrpNPb2dRaFlxTIEOR5Wim8oCOJTiGu2ruCoaM3cpDoDzb8pl13qfns02EBWVi9DjhtaMzJKZG1uTIdLKYTCT2MlZalJo5Lkk8zoStxfFXUhwHBdUkSBlGeGZt1W7GYHCB9uCrzsdkjkFoGT7UQ="
  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE

cache:
  directories:
    - '$HOME/.m2/repository'

script: ./travis.sh
